version: '3'
services:
  db:
    image: postgres:10.5
    environment:
      POSTGRES_USER: stackrating
      POSTGRES_PASSWORD: jUBwsv2QeSj5bem
      POSTGRES_DB: stackrating
    volumes:
      - ./data:/var/lib/postgresql/data
  service:
    image: openjdk:11-jre-slim
    volumes:
      - ./dist:/opt/stackrating
    working_dir: /opt/stackrating
    command: java -jar stackrating-1.1.jar
    ports:
      - 4567:4567
    depends_on:
      - db
  caddy:
    image: abiosoft/caddy:0.11.0-no-stats
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    environment:
     - ACME_AGREE=true
    ports:
      - "30080:80"
      - "30443:443"
    depends_on:
      - service
